---
- name: webserver setup
  hosts: webservers
  become: yes
  tasks:
    - name: install httpd
      ansible.builtin.yum:
        name: httpd
        state: present
    - name: start httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
    - name: copy index.html
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
