pipeline{
    agent any
    tools{
        maven "Maven3"
        jdk "JDK-11"
    }
    environment{
        registryCredential = 'ecr:ap-south-1:aws-ecr'
        appRegistry = "211125490320.dkr.ecr.ap-south-1.amazonaws.com/learning-jenkins-docker"
        jenkinsRegistry = 'https://211125490320.dkr.ecr.ap-south-1.amazonaws.com'
        cluster = "jenkins"
        service = "jenkinsappsvc"

    }
    stages{
        stage ("Fetch Code"){
            steps{
                git branch: 'docker', url:'https://github.com/devopshydclub/vprofile-project.git'
            }
        }
        stage ("Test"){
            steps{
                sh 'mvn test'
            }
        }
        stage ("Code Analysis with Checkstyle"){
            steps{
                sh 'mvn checkstyle:checkstyle'
            }
            post{
                success{
                echo "Generated Analysis Result"
                }
                
            }
        }
        stage('Build App Image') {
       steps {
       
         script {
                dockerImage = docker.build( appRegistry + ":$BUILD_NUMBER", "./Docker-files/app/multistage/")
             }

     }
    
    }
        stage("Upload App Image"){
            steps{
                script{
                    docker.withRegistry(jenkinsRegistry, registryCredential){
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push("latest")
                    }
                }
            }
        }
        stage("Deploy to ecs"){
            steps{
                withAWS(credentials: 'aws-ecr',region: 'ap-south-1'){
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }
}