all:
  hosts:
    web1:
      ansible_host: 172.31.9.56
    web2:
      ansible_host: 172.31.6.201
    db1:
      ansible_host: 172.31.4.87
  children:
    webservers:
      hosts:
        web1:
        web2:
    dbservers:
      hosts:
        db1:
    avengers:
      children:
        webservers:
        dbservers:
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: centos.pem
